name: ecmsp-full

services:

    cart-service:
        build:
            context: ../cart-service
            dockerfile: Dockerfile
        container_name: cart-service
        ports: 
            - "8000:8080"
        env_file:
            -
                path: ../cart-service/docker/app-env.txt 
                required: false 
        depends_on:
            cart-service-db:
                restart: true
                condition: service_healthy
    #

    cart-service-db:
        image: postgres:15-alpine
        container_name: cart-service-db
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""]
            interval: 10s
            retries: 5
            start_period: 30s
            timeout: 10s

        ports:
            - "9000:5432"
        volumes:
            - ../cart-service/docker/init.sql:/docker-entrypoint-initdb.d/init.sql
            - cart-service-db:/var/lib/postgresql/data
        secrets:
            - cart-service-db-password
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_DB=cart-service-db
            - POSTGRES_PASSWORD_FILE=/run/secrets/cart-service-db-password
        env_file:
            -
                path: ../cart-service/docker/database-env.txt
                required: false
    #    

# networks:
#     ecmsp-network:
#         driver: bridge

secrets:
    cart-service-db-password:
        file: ../cart-service/docker/database-password.txt 

volumes:
    cart-service-db:

# docker compose -f product-docker-compose.yaml up cart-service-db
# docker compose -f product-docker-compose.yaml down -v