name: ecmsp-dev

services:
    cart-service-db-dev:
        image: postgres:15-alpine
        container_name: cart-service-db-dev
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""]
            interval: 10s
            retries: 5
            start_period: 30s
            timeout: 10s

        ports:
            - "5432:5432"
        volumes:
            - cart-service-db:/var/lib/postgresql/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        secrets:
            - cart-service-db-password
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_DB=cart-service-db
            - POSTGRES_PASSWORD_FILE=/run/secrets/cart-service-db-password
        env_file:
            -
                path: ./database-env.txt
                required: false

volumes:
    cart-service-db:

secrets:
    cart-service-db-password:
        file: ./database-password.txt