build_windows:
	set GOOS=windows
	set GOARCH=amd64
	go build -o ../manager.exe main.go

build_macos:
	set GOOS=darwin
	set GOARCH=amd64
	go build -o ../manager-macos main.go

build_linux:
	set GOOS=linux
	set GOARCH=amd64
	go build -o ../manager-linux main.go