build_windows:
	GOOS=windows GOARCH=amd64 go build -o ../manager.exe main.go

build_macos:
	GOOS=darwin GOARCH=amd64 go build -o ../manager-macos main.go

build_linux:
	GOOS=linux GOARCH=amd64 go build -o ../manager-linux main.go